---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludo-app
  labels:
    app: ludo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ludo-app
  template:
    metadata:
      labels:
        app: ludo-app
    spec:
      containers:
      - name: ludo-container
        image: 560976331199.dkr.ecr.us-east-1.amazonaws.com/ludo:latest
        ports:
        - containerPort: 5173
...
